# Generated by Django 4.2.15 on 2025-09-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "index",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("image", models.ImageField(upload_to="gallery/originals/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
